language: java
email:
  recipients:
  - eamon.foy@mycit.ie
  - john.nolan1@mycit.ie
jdk:
- oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- ./mvnw test
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=BravoTeam2018_SAD-2 -Dsonar.organization=bravoteam2018-1 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=46b04871e22210fffd6ddf2b6ae5c82c5a2d8a08
env:
  global:
before_install:
- chmod +x mvnw
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: eamon.foy@mycit.ie
  password:
    secure: lbw8zN/hXZBxYdcopUcpt7fgt3ZHdNGwtJfg/3k8Sgikn1Q3Tk4agg5X0bGhQFHE67Xxe+4uhrKGUqXUEV4GIiJfHQ67L3PeHu4nU1Q6QzRGIBoN9nUpRNywBHMFSzfLZOgl5+6wt8rCSP7V9vgRjUbWxdBbG/VDuD0rAnMCtJiIGQhOz1gtukFq45y4OrHco/c9GC6DKMOn0bQTnuZe2wq3w7kk2LgbJ1DoSEwABXzOztnE1/+kf/Qio1HBZfKXbq5/Zc7oD/zGBPyl63uHO887bXiRW3q7d0cVCxjXD5B1IvjQkaD8YfFnyajow2qw4E/Qg9xhco3GrFsQQWKUSA4qKTETVs2CLVgCGwk12YXEyX30qJNRu200EHcjiWYISKtlmoKsB9qg47dtEy7TZ7WY2Xz4FJEz0mUT3F9p5RxK7I9NIzNWHn+FY5CeqMKBs/iECMq8N6TXi82omjkP87PBfbecfbKFreeSx6oMqXamR7CzdXC4CMJ3L2UQeVEIFAvO8DLlodHMmqjlW5YTXfR7riVM/iy+b94odYDrZ096Du1f7WupIxqoUWI+rjOpWSGKdcyiGVUmYeO3eLAJjLAl9xLCGww7OCLvVI69//9rDxLCD5M+4AbsdaDII5L3oZSkA3BKVRx/bW6FSllVUEDQ8kcB56Ewb+cnSWEuZW0=
  organization: WeFixItInc.org
  space: TeamBravo
  app: rfidclonespy
  skip_cleanup: true
  file: restapi/target/restapi-0.0.1-SNAPSHOT-exec.jar
  on:
    repo: BravoTeam2018/SAD-2   