      language: java
      email:
           recipients:
              - anna.odziemczyk@mycit.ie
              - eamon.foy@mycit.ie
              - john.nolan1@mycit.ie
      jdk:
      - oraclejdk8
      install:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script:
      - mvn test